### ISSUE TITLE
Create Hospital room assets

### ISSUE THREAD

**Issue by TabrisArg** [2B-Games/Lost-Conscience#10]
- [x] Hospital bed with covers
- [x] Music box (transport)
- [x] Book (transport)
- [x] Pen with pen holder (transport)
- [x] Window with outside scene
- [x] Old TV on the wall with support
- [x] bedside table
  - [x] place clock and music box on table
- [x] digital clock
- [x] walls, duh
- [x] door
- [x] ceiling fan
- [x] empty bed

**Comment by agerarg** [comment]
- [x] maquina que hace pip!

**Comment by TabrisArg** [comment]
- [x] IV with pipes
